#+title: Ejercicios de programación lineal
#+options: author:nil  ':t toc:nil
#+date: 20 de abril de 2020
#+language: es
#+latex_header: \usepackage[spanish]{babel}
#+latex_header: \usepackage[margin=3cm]{geometry}
#+latex_header: \usepackage{systeme}
# #+latex_class_options: [twocolumn]
#+latex: \thispagestyle{empty}

1. Demuestra el siguiente problema es insoluble y explica
   porqué.
   \begin{equation*}
    \begin{aligned}
   \text{Maximizar} \quad & x_{1}+4x_{2}\\
   \text{sujeto a} \quad &
     \begin{aligned}
      x_{1}+2x_{2} &\leq 5\\
      2x_{1}+x_{2} &= 4\\
      x_{1}-x_{2} &\geq 3\\
       x_{1}, x_{2} & \geq 0
     \end{aligned}
   \end{aligned}
   \end{equation*}
2. Cuando hay varias opciones entre las variables que podemos
   incrementar al usar el método simplex, es conveniente ser
   consistente en una regla para escoger la variable a incrementar. 

   Podemos escoger, digamos, siempre la variable con índice menor (por
   ejemplo, si podemos aumentar \(x_{2},x_{3},x_{7}\), escogeríamos la
   \(x_{2}\). Si podemos aumentar, digamos \(x_{5},x_{6}\), escogemos
   \(x_{5}\)). Otra regla es escoger siempre la variable que tiene el
   coeficiente más grande.
 
   Compara el desempeño de las reglas:
   - variable con índice más pequeño,
   - variable con coeficiente mayor,
     al aplicar el método simplex al siguiente problema:
    \begin{equation*}
     \begin{aligned}
    \text{Maximizar} \quad & 3x_{1}+5x_{2}\\
    \text{sujeto a} \quad &
      \begin{aligned}
       x_{1}+2x_{2}&\leq 5\\
       x_{1}  &\leq 3\\
       x_{2}  &\leq 2\\
	x_{1},x_{2} &\geq 0
      \end{aligned}
    \end{aligned}
    \end{equation*}
3. Igual que el ejercicio anterior, para el problema:
    \begin{equation*}
     \begin{aligned}
    \text{Maximizar} \quad & 2x_{1}+x_{2}\\
    \text{sujeto a} \quad &
      \begin{aligned}
       3x_{1}+x_{2}&\leq 3\\
	x_{1},x_{2} &\geq 0
      \end{aligned}
    \end{aligned}
    \end{equation*}
