#+title: Ejercicios de programación lineal
#+options: author:nil  ':t toc:nil
#+date: 2 de marzo de 2020
#+language: es
#+latex_header: \usepackage[spanish]{babel}
#+latex_header: \usepackage[margin=3cm]{geometry}
#+latex_class_options: [twocolumn]
#+latex: \thispagestyle{empty}

1. Resuelve el problema por el método simplex. 
  \begin{equation*}
   \begin{aligned}
  \text{Maximizar} \quad & 2x_{1}+x_{2}\\
  \text{sujeto a} \quad &
    \begin{aligned}
     x_{1}+x_{2} &\geq 1\\
     3x_{1}+4x_{2} &\leq 12\\
     x_{1}-x_{2} &\leq 2\\
     -2x_{1}+x_{2} &\leq 2\\
      x_{1},x_{2} &\geq 0
    \end{aligned}
  \end{aligned}
  \end{equation*}

2. Considera el siguiente problema:
   \begin{equation*}
   \begin{aligned}
   \text{Maximizar} \quad & 4x_{1}+x_{2}+3x_{3}\\
   \text{sujeto a} \quad &
     \begin{aligned}
      x_{1} & \leq 3\\
      x_{2} &\leq 5\\
      x_{3} &\leq 2\\
      x_{1}+x_{2}+2x_{3} &\leq 10\\
      x_{1},x_{2},x_{3} &\geq 0
     \end{aligned}
   \end{aligned}
   \end{equation*}

   - Escribe el problema en su forma estándar, determinando \(A\),
     \(b\) y \(c\).
   - Resuelve el problema por el método simplex.

3. Resuelve el siguiente problema:
   \begin{equation*}
   \begin{aligned}
   \text{Maximizar} \quad & 4x_{1}+5x_{2}\\
   \text{sujeto a} \quad &
     \begin{aligned}
      -x_{1}+x_{2} &\leq 4\\
      x_{1}+x_{2} &\leq 6\\
      x_{1},x_{2} &\geq  0
     \end{aligned}
   \end{aligned}
   \end{equation*}

4. Un fabricante produce dos tipos de ropa: \(T_{1}\) y
   \(T_{2}\). Para producir una unidad de \(T_{1}\) se necesitan 4
   unidades de la materia prima \(R1\), 5 unidaes de materia prima
   \(R2\) y una unidad de la materia prima \(R3\). Para producir una
   unidad de \(T_{2}\) los requerimientos, en el mismo orden, son 1, 3
   y 2 unidades, respectivamente. Las cantidades disponibles de \(R1,
   R2\) y \(R3\) son: 56, 105 y 56, respectivamente.

   Si la ganancia de la venta de una unidad de \(T_{1}\) es de $4 y la
   de una unidad de \(T_{2}\) es $5, ¿cuánto se debe producir de
   \(T_{1}\) y \(T_{2}\) para maximizar las ganancias?

5. Dos problemas de programación lineal tienen regiones factibles
   definidas como:
   \begin{equation*}
     \begin{aligned}
      x_{1}+x_{2} & \leq 6\\
      x_{1}+2x_{2} & \leq 10\\
      x_{1},x_{2} &\geq 0
     \end{aligned}
   \end{equation*}
   y
   \begin{equation*}
     \begin{aligned}
      x_{1}+x_{2}+x_{3} & = 6\\
      x_{1}+2x_{2}+x_{3} & =10\\
      x_{1},x_{2},x_{3} &\geq 0
     \end{aligned}
   \end{equation*}
   Demuestra que los problemas no son equivalentes. [Sugerencia:
   \(x_{1}=3\), \(x_{2}=3\) satisface las restricciones del primer
   problema. ¿Existe un valor de \(x_{3}\) tal que \((3,3,x_{3})\)
   satisfaga las restricciones del segundo problema?] Esto muestra que
   no se puede usar la misma variable de holgura para diferentes
   desigualdades. 



